GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "Testing blog 2",
  "author": "Random ",
  "url": "https://fullstackopen.com",
  "likes": 1
}

###
POST http://localhost:3003/api/users
content-type: application/json

{
  "username": "mluukkai",
  "name": "Matti Luukkainen",
  "password": "salainen"
}

###
POST http://localhost:3003/api/users
content-type: application/json

{
  "username": "he",
  "name": "Arto Hellas",
  "password": "123456"
}