GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "Testing blog 2",
  "author": "Random ",
  "url": "https://fullstackopen.com",
  "likes": 1
}

###
POST http://localhost:3003/api/users
content-type: application/json

{
  "username": "mluukkai",
  "name": "Matti Luukkainen",
  "password": "salainen"
}

### invalid user creation
POST http://localhost:3003/api/users
content-type: application/json

{
  "username": "heluo",
  "name": "Arto Hellas",
  "password": "123456"
}

### login
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "heluo",
  "password": "123456"
}

### create new note with authorization token
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbHVvIiwiaWQiOiI2OWEzZDVmNWZiZDY5NWJhYTZhZDI1OGUiLCJpYXQiOjE3NzIzNDU4ODR9.k596KfGrUfM1EmcVsQ6asuh8Ih5CISArsfybGQhw6oM

{
  "title": "Testing blog 5",
  "author": "Random 5",
  "url": "https://fullstackopen.com",
  "likes": 1
}